### ISSUE TITLE
Publish link to CEWS registry

### ISSUE THREAD

**Issue by 2denise** [gc-proto/covid-19-guidance#90] opened 2020-09-08 20:45 UTC
Adding link to ITB application listing CEWS recipients from CEWS secondary navigation. Goals is to have this published by June 22 (per Claude on June 18).
Mock-up: http://test.canada.ca/covid-19-guidance/proto/wage-subsidy/how-much.html

**Comment by LMElston** [comment] 2020-09-09 13:57
Closing as duplicate of issue #19

**Closed by LMElston** 2020-09-09 13:57 UTC
Labels: CEWS
